variables:
  REQUIREMENTS: "requirements.txt"

stages:
  - test

.test: &test
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y nodejs
    - python --version
    - pip install -r requirements.txt
    - export PYTHONPATH=$(pwd):$PYTHONPATH
  script:
    - python -m unittest discover

# Test with python 3.6
test:3.6:
  <<: *test
  image: python:3.6

# Test with python 3.7
test:3.7:
  <<: *test
  image: python:3.7-stretch

# Test with python 3.8
test:3.8:
  <<: *test
  image: python:3.8-buster
